import { config } from 'dotenv';
config({ path: '.env.local' });

import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

const supabase = createClient(supabaseUrl, supabaseServiceKey);

// 50 curated NFL legends and current stars with complete, accurate data
const curatedPlayers = [
  // Legendary Quarterbacks
  {
    name: 'Tom Brady',
    sport: 'nfl',
    birth_city: 'San Mateo',
    birth_state: 'California',
    birth_country: 'USA',
    latitude: 37.5630,
    longitude: -122.3255,
    position: 'QB',
    team: 'New England Patriots',
    years_active: '2000-2023',
    is_active: false,
    difficulty_level: 'easy',
    city_fact: 'San Mateo is located in the heart of Silicon Valley, just south of San Francisco. The city is known for its mild Mediterranean climate and is home to major tech companies.',
    photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Tom_Brady_2022.jpg/440px-Tom_Brady_2022.jpg'
  },
  {
    name: 'Joe Montana',
    sport: 'nfl',
    birth_city: 'New Eagle',
    birth_state: 'Pennsylvania',
    birth_country: 'USA',
    latitude: 40.2034,
    longitude: -79.9517,
    position: 'QB',
    team: 'San Francisco 49ers',
    years_active: '1979-1994',
    is_active: false,
    difficulty_level: 'easy',
    city_fact: 'New Eagle is a small borough in Washington County, Pennsylvania with a population under 2,000. It sits along the Monongahela River, about 20 miles south of Pittsburgh.',
    photo_url: null
  },
  {
    name: 'Peyton Manning',
    sport: 'nfl',
    birth_city: 'New Orleans',
    birth_state: 'Louisiana',
    birth_country: 'USA',
    latitude: 29.9511,
    longitude: -90.0715,
    position: 'QB',
    team: 'Indianapolis Colts',
    years_active: '1998-2015',
    is_active: false,
    difficulty_level: 'easy',
    city_fact: 'New Orleans is the birthplace of jazz music, famous for its vibrant culture, Creole cuisine, French Quarter, and the annual Mardi Gras celebration.',
    photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Peyton_Manning_%282012%29.jpg/440px-Peyton_Manning_%282012%29.jpg'
  },
  {
    name: 'Dan Marino',
    sport: 'nfl',
    birth_city: 'Pittsburgh',
    birth_state: 'Pennsylvania',
    birth_country: 'USA',
    latitude: 40.4406,
    longitude: -79.9959,
    position: 'QB',
    team: 'Miami Dolphins',
    years_active: '1983-1999',
    is_active: false,
    difficulty_level: 'medium',
    city_fact: 'Pittsburgh is known as the "City of Bridges" with 446 bridges, more than any other city in the world. It has a rich steel industry history and sits at the confluence of three rivers.',
    photo_url: null
  },
  {
    name: 'Brett Favre',
    sport: 'nfl',
    birth_city: 'Gulfport',
    birth_state: 'Mississippi',
    birth_country: 'USA',
    latitude: 30.3674,
    longitude: -89.0928,
    position: 'QB',
    team: 'Green Bay Packers',
    years_active: '1991-2010',
    is_active: false,
    difficulty_level: 'easy',
    city_fact: 'Gulfport is the second-largest city in Mississippi and sits on the Gulf of Mexico. It\'s known for its beautiful beaches, casinos, and as a major port city.',
    photo_url: null
  },
  {
    name: 'John Elway',
    sport: 'nfl',
    birth_city: 'Port Angeles',
    birth_state: 'Washington',
    birth_country: 'USA',
    latitude: 48.1181,
    longitude: -123.4307,
    position: 'QB',
    team: 'Denver Broncos',
    years_active: '1983-1998',
    is_active: false,
    difficulty_level: 'medium',
    city_fact: 'Port Angeles sits on the northern edge of the Olympic Peninsula along the Strait of Juan de Fuca. It serves as a gateway to Olympic National Park and offers ferry service to Victoria, BC.',
    photo_url: null
  },
  {
    name: 'Troy Aikman',
    sport: 'nfl',
    birth_city: 'West Covina',
    birth_state: 'California',
    birth_country: 'USA',
    latitude: 34.0686,
    longitude: -117.9390,
    position: 'QB',
    team: 'Dallas Cowboys',
    years_active: '1989-2000',
    is_active: false,
    difficulty_level: 'medium',
    city_fact: 'West Covina is a suburban city in Los Angeles County, located about 20 miles east of downtown Los Angeles. The city grew significantly after World War II.',
    photo_url: null
  },
  {
    name: 'Aaron Rodgers',
    sport: 'nfl',
    birth_city: 'Chico',
    birth_state: 'California',
    birth_country: 'USA',
    latitude: 39.7285,
    longitude: -121.8375,
    position: 'QB',
    team: 'Green Bay Packers',
    years_active: '2005-present',
    is_active: true,
    difficulty_level: 'easy',
    city_fact: 'Chico is home to California State University, Chico and features Bidwell Park, one of the largest municipal parks in the United States at over 3,600 acres.',
    photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Aaron_Rodgers_%2851959031202%29_%28cropped%29.jpg/440px-Aaron_Rodgers_%2851959031202%29_%28cropped%29.jpg'
  },
  {
    name: 'Patrick Mahomes',
    sport: 'nfl',
    birth_city: 'Tyler',
    birth_state: 'Texas',
    birth_country: 'USA',
    latitude: 32.3513,
    longitude: -95.3011,
    position: 'QB',
    team: 'Kansas City Chiefs',
    years_active: '2017-present',
    is_active: true,
    difficulty_level: 'easy',
    city_fact: 'Tyler is known as the "Rose Capital of America" and hosts the largest rose garden in the United States, producing over 20% of the nation\'s rose bushes.',
    photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Patrick_Mahomes_in_2022.jpg/440px-Patrick_Mahomes_in_2022.jpg'
  },
  {
    name: 'Josh Allen',
    sport: 'nfl',
    birth_city: 'Firebaugh',
    birth_state: 'California',
    birth_country: 'USA',
    latitude: 36.8586,
    longitude: -120.4560,
    position: 'QB',
    team: 'Buffalo Bills',
    years_active: '2018-present',
    is_active: true,
    difficulty_level: 'medium',
    city_fact: 'Firebaugh is a small agricultural city in Fresno County, California. The area is known for its farming and is located in the heart of California\'s Central Valley.',
    photo_url: null
  },

  // Legendary Running Backs
  {
    name: 'Walter Payton',
    sport: 'nfl',
    birth_city: 'Columbia',
    birth_state: 'Mississippi',
    birth_country: 'USA',
    latitude: 31.2946,
    longitude: -89.8365,
    position: 'RB',
    team: 'Chicago Bears',
    years_active: '1975-1987',
    is_active: false,
    difficulty_level: 'medium',
    city_fact: 'Columbia is a small city in southern Mississippi, known as the birthplace of several notable figures. The city sits along the Pearl River and has a rich lumber industry history.',
    photo_url: null
  },
  {
    name: 'Barry Sanders',
    sport: 'nfl',
    birth_city: 'Wichita',
    birth_state: 'Kansas',
    birth_country: 'USA',
    latitude: 37.6872,
    longitude: -97.3301,
    position: 'RB',
    team: 'Detroit Lions',
    years_active: '1989-1998',
    is_active: false,
    difficulty_level: 'medium',
    city_fact: 'Wichita is the largest city in Kansas and is known as the "Air Capital of the World" due to its history of aircraft manufacturing. Companies like Cessna and Beechcraft are based there.',
    photo_url: null
  },
  {
    name: 'Emmitt Smith',
    sport: 'nfl',
    birth_city: 'Pensacola',
    birth_state: 'Florida',
    birth_country: 'USA',
    latitude: 30.4213,
    longitude: -87.2169,
    position: 'RB',
    team: 'Dallas Cowboys',
    years_active: '1990-2004',
    is_active: false,
    difficulty_level: 'easy',
    city_fact: 'Pensacola is known as the "City of Five Flags" due to the five governments that have ruled it. The city is home to the Blue Angels, the U.S. Navy\'s flight demonstration squadron.',
    photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Emmitt_Smith_in_2017.jpg/440px-Emmitt_Smith_in_2017.jpg'
  },
  {
    name: 'Jim Brown',
    sport: 'nfl',
    birth_city: 'St. Simons',
    birth_state: 'Georgia',
    birth_country: 'USA',
    latitude: 31.1516,
    longitude: -81.3873,
    position: 'RB',
    team: 'Cleveland Browns',
    years_active: '1957-1965',
    is_active: false,
    difficulty_level: 'hard',
    city_fact: 'St. Simons Island is one of the Golden Isles of Georgia, known for its beaches, historic lighthouse, and as a popular vacation destination on the Atlantic coast.',
    photo_url: null
  },
  {
    name: 'LaDainian Tomlinson',
    sport: 'nfl',
    birth_city: 'Rosebud',
    birth_state: 'Texas',
    birth_country: 'USA',
    latitude: 31.0738,
    longitude: -96.9764,
    position: 'RB',
    team: 'San Diego Chargers',
    years_active: '2001-2011',
    is_active: false,
    difficulty_level: 'medium',
    city_fact: 'Rosebud is a small town in Falls County, Texas, located between Waco and Austin. The area is known for its agricultural heritage.',
    photo_url: null
  },
  {
    name: 'Eric Dickerson',
    sport: 'nfl',
    birth_city: 'Sealy',
    birth_state: 'Texas',
    birth_country: 'USA',
    latitude: 29.7808,
    longitude: -96.1594,
    position: 'RB',
    team: 'Los Angeles Rams',
    years_active: '1983-1993',
    is_active: false,
    difficulty_level: 'medium',
    city_fact: 'Sealy is a city in Austin County, Texas, known as a major shipping point for cotton and grain. It\'s located about 50 miles west of Houston.',
    photo_url: null
  },

  // Wide Receivers
  {
    name: 'Jerry Rice',
    sport: 'nfl',
    birth_city: 'Starkville',
    birth_state: 'Mississippi',
    birth_country: 'USA',
    latitude: 33.4504,
    longitude: -88.8184,
    position: 'WR',
    team: 'San Francisco 49ers',
    years_active: '1985-2004',
    is_active: false,
    difficulty_level: 'easy',
    city_fact: 'Starkville is home to Mississippi State University and is known as "Mississippi\'s College Town." The city is located in the Golden Triangle region of Mississippi.',
    photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Jerry_Rice_at_Super_Bowl_50.jpg/440px-Jerry_Rice_at_Super_Bowl_50.jpg'
  },
  {
    name: 'Randy Moss',
    sport: 'nfl',
    birth_city: 'Rand',
    birth_state: 'West Virginia',
    birth_country: 'USA',
    latitude: 38.2815,
    longitude: -81.5593,
    position: 'WR',
    team: 'Minnesota Vikings',
    years_active: '1998-2012',
    is_active: false,
    difficulty_level: 'medium',
    city_fact: 'Rand is a small unincorporated community in Kanawha County, West Virginia. The area is known for its Appalachian heritage and proximity to Charleston, the state capital.',
    photo_url: null
  },
  {
    name: 'Terrell Owens',
    sport: 'nfl',
    birth_city: 'Alexander City',
    birth_state: 'Alabama',
    birth_country: 'USA',
    latitude: 32.9440,
    longitude: -85.9538,
    position: 'WR',
    team: 'San Francisco 49ers',
    years_active: '1996-2010',
    is_active: false,
    difficulty_level: 'medium',
    city_fact: 'Alexander City is located on the shores of Lake Martin in east-central Alabama. The city was a major textile manufacturing center in the 20th century.',
    photo_url: null
  },
  {
    name: 'Calvin Johnson',
    sport: 'nfl',
    birth_city: 'Newnan',
    birth_state: 'Georgia',
    birth_country: 'USA',
    latitude: 33.3807,
    longitude: -84.7997,
    position: 'WR',
    team: 'Detroit Lions',
    years_active: '2007-2015',
    is_active: false,
    difficulty_level: 'medium',
    city_fact: 'Newnan is known as the "City of Homes" due to its many historic residences. Located southwest of Atlanta, it served as a hospital city during the Civil War.',
    photo_url: null
  },
  {
    name: 'Larry Fitzgerald',
    sport: 'nfl',
    birth_city: 'Minneapolis',
    birth_state: 'Minnesota',
    birth_country: 'USA',
    latitude: 44.9778,
    longitude: -93.2650,
    position: 'WR',
    team: 'Arizona Cardinals',
    years_active: '2004-2020',
    is_active: false,
    difficulty_level: 'medium',
    city_fact: 'Minneapolis is the largest city in Minnesota, known as the "City of Lakes" with over 20 lakes within city limits. It\'s part of the Twin Cities with neighboring St. Paul.',
    photo_url: null
  },

  // Defensive Legends
  {
    name: 'Lawrence Taylor',
    sport: 'nfl',
    birth_city: 'Williamsburg',
    birth_state: 'Virginia',
    birth_country: 'USA',
    latitude: 37.2707,
    longitude: -76.7075,
    position: 'LB',
    team: 'New York Giants',
    years_active: '1981-1993',
    is_active: false,
    difficulty_level: 'medium',
    city_fact: 'Williamsburg is a historic city known for Colonial Williamsburg, a living-history museum. It was the capital of Virginia from 1699 to 1780.',
    photo_url: null
  },
  {
    name: 'Ray Lewis',
    sport: 'nfl',
    birth_city: 'Bartow',
    birth_state: 'Florida',
    birth_country: 'USA',
    latitude: 27.8964,
    longitude: -81.8431,
    position: 'LB',
    team: 'Baltimore Ravens',
    years_active: '1996-2012',
    is_active: false,
    difficulty_level: 'medium',
    city_fact: 'Bartow is the county seat of Polk County in central Florida. The city is known for its historic downtown and proximity to numerous lakes.',
    photo_url: null
  },
  {
    name: 'Reggie White',
    sport: 'nfl',
    birth_city: 'Chattanooga',
    birth_state: 'Tennessee',
    birth_country: 'USA',
    latitude: 35.0456,
    longitude: -85.3097,
    position: 'DE',
    team: 'Green Bay Packers',
    years_active: '1985-2000',
    is_active: false,
    difficulty_level: 'medium',
    city_fact: 'Chattanooga is known as the "Scenic City" due to its location in the Tennessee Valley surrounded by mountains. It\'s famous for Ruby Falls and Rock City.',
    photo_url: null
  },
  {
    name: 'Deion Sanders',
    sport: 'nfl',
    birth_city: 'Fort Myers',
    birth_state: 'Florida',
    birth_country: 'USA',
    latitude: 26.6406,
    longitude: -81.8723,
    position: 'CB',
    team: 'Dallas Cowboys',
    years_active: '1989-2005',
    is_active: false,
    difficulty_level: 'easy',
    city_fact: 'Fort Myers is known as the "City of Palms" and was the winter home of Thomas Edison and Henry Ford. The city sits on the Caloosahatchee River.',
    photo_url: null
  },
  {
    name: 'Ed Reed',
    sport: 'nfl',
    birth_city: 'St. Rose',
    birth_state: 'Louisiana',
    birth_country: 'USA',
    latitude: 29.9502,
    longitude: -90.3198,
    position: 'S',
    team: 'Baltimore Ravens',
    years_active: '2002-2013',
    is_active: false,
    difficulty_level: 'hard',
    city_fact: 'St. Rose is a small census-designated place in St. Charles Parish, Louisiana, on the east bank of the Mississippi River about 20 miles west of New Orleans.',
    photo_url: null
  },
  {
    name: 'Ronnie Lott',
    sport: 'nfl',
    birth_city: 'Albuquerque',
    birth_state: 'New Mexico',
    birth_country: 'USA',
    latitude: 35.0844,
    longitude: -106.6504,
    position: 'S',
    team: 'San Francisco 49ers',
    years_active: '1981-1994',
    is_active: false,
    difficulty_level: 'medium',
    city_fact: 'Albuquerque is the largest city in New Mexico, known for the annual International Balloon Fiesta. The city sits in the high desert of central New Mexico.',
    photo_url: null
  },
  {
    name: 'Dick Butkus',
    sport: 'nfl',
    birth_city: 'Chicago',
    birth_state: 'Illinois',
    birth_country: 'USA',
    latitude: 41.8781,
    longitude: -87.6298,
    position: 'LB',
    team: 'Chicago Bears',
    years_active: '1965-1973',
    is_active: false,
    difficulty_level: 'medium',
    city_fact: 'Chicago is the third-largest city in the US, famous for its architecture, deep-dish pizza, and being the birthplace of the skyscraper. It sits on Lake Michigan.',
    photo_url: null
  },

  // Offensive Linemen
  {
    name: 'Anthony Muñoz',
    sport: 'nfl',
    birth_city: 'Ontario',
    birth_state: 'California',
    birth_country: 'USA',
    latitude: 34.0633,
    longitude: -117.6509,
    position: 'OT',
    team: 'Cincinnati Bengals',
    years_active: '1980-1992',
    is_active: false,
    difficulty_level: 'medium',
    city_fact: 'Ontario is a city in San Bernardino County, about 35 miles east of Los Angeles. It\'s home to Ontario International Airport and the Ontario Mills shopping center.',
    photo_url: null
  },
  {
    name: 'Jonathan Ogden',
    sport: 'nfl',
    birth_city: 'Washington',
    birth_state: 'District of Columbia',
    birth_country: 'USA',
    latitude: 38.9072,
    longitude: -77.0369,
    position: 'OT',
    team: 'Baltimore Ravens',
    years_active: '1996-2007',
    is_active: false,
    difficulty_level: 'medium',
    city_fact: 'Washington, D.C. is the capital of the United States, home to the White House, Capitol Building, and Smithsonian museums. The city sits on the Potomac River.',
    photo_url: null
  },

  // Tight Ends
  {
    name: 'Tony Gonzalez',
    sport: 'nfl',
    birth_city: 'Torrance',
    birth_state: 'California',
    birth_country: 'USA',
    latitude: 33.8358,
    longitude: -118.3406,
    position: 'TE',
    team: 'Kansas City Chiefs',
    years_active: '1997-2013',
    is_active: false,
    difficulty_level: 'medium',
    city_fact: 'Torrance is a coastal city in Los Angeles County, known for its beaches and as the North American headquarters of Honda and Toyota.',
    photo_url: null
  },
  {
    name: 'Rob Gronkowski',
    sport: 'nfl',
    birth_city: 'Amherst',
    birth_state: 'New York',
    birth_country: 'USA',
    latitude: 42.9784,
    longitude: -78.7997,
    position: 'TE',
    team: 'New England Patriots',
    years_active: '2010-2021',
    is_active: false,
    difficulty_level: 'easy',
    city_fact: 'Amherst is a suburb of Buffalo in Western New York, known for the University at Buffalo campus. It\'s one of the largest towns in New York by population.',
    photo_url: null
  },

  // More Recent Stars
  {
    name: 'Odell Beckham Jr.',
    sport: 'nfl',
    birth_city: 'Baton Rouge',
    birth_state: 'Louisiana',
    birth_country: 'USA',
    latitude: 30.4515,
    longitude: -91.1871,
    position: 'WR',
    team: 'New York Giants',
    years_active: '2014-present',
    is_active: true,
    difficulty_level: 'easy',
    city_fact: 'Baton Rouge is the capital of Louisiana, located on the Mississippi River. The city is home to Louisiana State University (LSU) and known for its Cajun culture.',
    photo_url: null
  },
  {
    name: 'J.J. Watt',
    sport: 'nfl',
    birth_city: 'Waukesha',
    birth_state: 'Wisconsin',
    birth_country: 'USA',
    latitude: 43.0117,
    longitude: -88.2315,
    position: 'DE',
    team: 'Houston Texans',
    years_active: '2011-2022',
    is_active: false,
    difficulty_level: 'easy',
    city_fact: 'Waukesha is a city west of Milwaukee, known for its historic downtown and annual Christmas parade. The city sits in southeastern Wisconsin.',
    photo_url: null
  },
  {
    name: 'Aaron Donald',
    sport: 'nfl',
    birth_city: 'Pittsburgh',
    birth_state: 'Pennsylvania',
    birth_country: 'USA',
    latitude: 40.4406,
    longitude: -79.9959,
    position: 'DT',
    team: 'Los Angeles Rams',
    years_active: '2014-2023',
    is_active: false,
    difficulty_level: 'easy',
    city_fact: 'Pittsburgh is known as the "City of Bridges" with 446 bridges. It has a rich steel industry history and sits at the confluence of three rivers.',
    photo_url: null
  },
  {
    name: 'Von Miller',
    sport: 'nfl',
    birth_city: 'DeSoto',
    birth_state: 'Texas',
    birth_country: 'USA',
    latitude: 32.5896,
    longitude: -96.8570,
    position: 'LB',
    team: 'Denver Broncos',
    years_active: '2011-present',
    is_active: true,
    difficulty_level: 'medium',
    city_fact: 'DeSoto is a suburb of Dallas in the Dallas-Fort Worth metroplex. The city has grown rapidly since the 1970s and is known for its diverse community.',
    photo_url: null
  },
  {
    name: 'Khalil Mack',
    sport: 'nfl',
    birth_city: 'Fort Pierce',
    birth_state: 'Florida',
    birth_country: 'USA',
    latitude: 27.4467,
    longitude: -80.3256,
    position: 'LB',
    team: 'Chicago Bears',
    years_active: '2014-present',
    is_active: true,
    difficulty_level: 'medium',
    city_fact: 'Fort Pierce is located on Florida\'s Treasure Coast along the Atlantic Ocean. The city is known for its beaches, fishing, and as the birthplace of Zora Neale Hurston.',
    photo_url: null
  },
  {
    name: 'Travis Kelce',
    sport: 'nfl',
    birth_city: 'Westlake',
    birth_state: 'Ohio',
    birth_country: 'USA',
    latitude: 41.4551,
    longitude: -81.9179,
    position: 'TE',
    team: 'Kansas City Chiefs',
    years_active: '2013-present',
    is_active: true,
    difficulty_level: 'easy',
    city_fact: 'Westlake is a suburb of Cleveland in northeastern Ohio. The city is known for its highly-rated schools and Crocker Park shopping district.',
    photo_url: null
  },
  {
    name: 'Tyreek Hill',
    sport: 'nfl',
    birth_city: 'Pearson',
    birth_state: 'Georgia',
    birth_country: 'USA',
    latitude: 31.2963,
    longitude: -82.8526,
    position: 'WR',
    team: 'Miami Dolphins',
    years_active: '2016-present',
    is_active: true,
    difficulty_level: 'medium',
    city_fact: 'Pearson is a small city in Atkinson County in south-central Georgia. The area is known for its agricultural heritage, particularly peanut farming.',
    photo_url: null
  },
  {
    name: 'Davante Adams',
    sport: 'nfl',
    birth_city: 'Redwood City',
    birth_state: 'California',
    birth_country: 'USA',
    latitude: 37.4852,
    longitude: -122.2364,
    position: 'WR',
    team: 'Las Vegas Raiders',
    years_active: '2014-present',
    is_active: true,
    difficulty_level: 'medium',
    city_fact: 'Redwood City is located in Silicon Valley on the San Francisco Peninsula. The city motto is "Climate Best by Government Test" referring to its ideal weather.',
    photo_url: null
  },
  {
    name: 'Cooper Kupp',
    sport: 'nfl',
    birth_city: 'Yakima',
    birth_state: 'Washington',
    birth_country: 'USA',
    latitude: 46.6021,
    longitude: -120.5059,
    position: 'WR',
    team: 'Los Angeles Rams',
    years_active: '2017-present',
    is_active: true,
    difficulty_level: 'medium',
    city_fact: 'Yakima is located in south-central Washington in the Yakima Valley. The area is known for its apple orchards, vineyards, and hop farming.',
    photo_url: null
  },
  {
    name: 'Derrick Henry',
    sport: 'nfl',
    birth_city: 'Yulee',
    birth_state: 'Florida',
    birth_country: 'USA',
    latitude: 30.6319,
    longitude: -81.6056,
    position: 'RB',
    team: 'Tennessee Titans',
    years_active: '2016-present',
    is_active: true,
    difficulty_level: 'medium',
    city_fact: 'Yulee is a small town in Nassau County in northeast Florida, near the Georgia border. The area is known for its rural character and proximity to Amelia Island.',
    photo_url: null
  },
  {
    name: 'Saquon Barkley',
    sport: 'nfl',
    birth_city: 'Bronx',
    birth_state: 'New York',
    birth_country: 'USA',
    latitude: 40.8448,
    longitude: -73.8648,
    position: 'RB',
    team: 'New York Giants',
    years_active: '2018-present',
    is_active: true,
    difficulty_level: 'easy',
    city_fact: 'The Bronx is the northernmost borough of New York City, known as the birthplace of hip hop. It\'s home to Yankee Stadium and the Bronx Zoo.',
    photo_url: null
  },
  {
    name: 'Christian McCaffrey',
    sport: 'nfl',
    birth_city: 'Castle Rock',
    birth_state: 'Colorado',
    birth_country: 'USA',
    latitude: 39.3722,
    longitude: -104.8561,
    position: 'RB',
    team: 'San Francisco 49ers',
    years_active: '2017-present',
    is_active: true,
    difficulty_level: 'medium',
    city_fact: 'Castle Rock is a fast-growing town between Denver and Colorado Springs. It\'s known for its distinctive rock formation and outlet shopping.',
    photo_url: null
  },
  {
    name: 'Jalen Ramsey',
    sport: 'nfl',
    birth_city: 'Smyrna',
    birth_state: 'Tennessee',
    birth_country: 'USA',
    latitude: 35.9828,
    longitude: -86.5186,
    position: 'CB',
    team: 'Los Angeles Rams',
    years_active: '2016-present',
    is_active: true,
    difficulty_level: 'medium',
    city_fact: 'Smyrna is a suburb of Nashville in Middle Tennessee. The town is home to Nissan\'s North American manufacturing headquarters.',
    photo_url: null
  },
  {
    name: 'Myles Garrett',
    sport: 'nfl',
    birth_city: 'Arlington',
    birth_state: 'Texas',
    birth_country: 'USA',
    latitude: 32.7357,
    longitude: -97.1081,
    position: 'DE',
    team: 'Cleveland Browns',
    years_active: '2017-present',
    is_active: true,
    difficulty_level: 'medium',
    city_fact: 'Arlington is located between Dallas and Fort Worth, home to AT&T Stadium (Dallas Cowboys) and Globe Life Field (Texas Rangers).',
    photo_url: null
  },
  {
    name: 'T.J. Watt',
    sport: 'nfl',
    birth_city: 'Pewaukee',
    birth_state: 'Wisconsin',
    birth_country: 'USA',
    latitude: 43.0806,
    longitude: -88.2612,
    position: 'LB',
    team: 'Pittsburgh Steelers',
    years_active: '2017-present',
    is_active: true,
    difficulty_level: 'medium',
    city_fact: 'Pewaukee is a city and village in Waukesha County, Wisconsin, located on Pewaukee Lake. It\'s a western suburb of Milwaukee.',
    photo_url: null
  },
  {
    name: 'Nick Bosa',
    sport: 'nfl',
    birth_city: 'Fort Lauderdale',
    birth_state: 'Florida',
    birth_country: 'USA',
    latitude: 26.1224,
    longitude: -80.1373,
    position: 'DE',
    team: 'San Francisco 49ers',
    years_active: '2019-present',
    is_active: true,
    difficulty_level: 'medium',
    city_fact: 'Fort Lauderdale is known as the "Venice of America" due to its extensive canal system. The city is famous for its beaches and yachting.',
    photo_url: null
  },
  {
    name: 'Justin Jefferson',
    sport: 'nfl',
    birth_city: 'St. Rose',
    birth_state: 'Louisiana',
    birth_country: 'USA',
    latitude: 29.9502,
    longitude: -90.3198,
    position: 'WR',
    team: 'Minnesota Vikings',
    years_active: '2020-present',
    is_active: true,
    difficulty_level: 'easy',
    city_fact: 'St. Rose is a small census-designated place in St. Charles Parish, Louisiana, on the east bank of the Mississippi River about 20 miles west of New Orleans.',
    photo_url: null
  },
  {
    name: 'Micah Parsons',
    sport: 'nfl',
    birth_city: 'Harrisburg',
    birth_state: 'Pennsylvania',
    birth_country: 'USA',
    latitude: 40.2737,
    longitude: -76.8844,
    position: 'LB',
    team: 'Dallas Cowboys',
    years_active: '2021-present',
    is_active: true,
    difficulty_level: 'medium',
    city_fact: 'Harrisburg is the capital of Pennsylvania, located on the Susquehanna River. The city played a crucial role in the Civil War and the Underground Railroad.',
    photo_url: null
  },
  {
    name: 'Ja\'Marr Chase',
    sport: 'nfl',
    birth_city: 'Harvey',
    birth_state: 'Louisiana',
    birth_country: 'USA',
    latitude: 29.9035,
    longitude: -90.0770,
    position: 'WR',
    team: 'Cincinnati Bengals',
    years_active: '2021-present',
    is_active: true,
    difficulty_level: 'medium',
    city_fact: 'Harvey is a suburb of New Orleans on the West Bank of the Mississippi River. The area was heavily affected by Hurricane Katrina in 2005.',
    photo_url: null
  },
];

async function seedPlayers() {
  console.log('Seeding curated NFL players...');

  // Clear existing players
  console.log('Clearing existing players...');
  const { error: deleteError } = await supabase
    .from('players')
    .delete()
    .neq('id', '00000000-0000-0000-0000-000000000000');

  if (deleteError) {
    console.error('Error clearing players:', deleteError);
    return;
  }

  console.log(`Inserting ${curatedPlayers.length} curated players...`);
  
  const { data, error } = await supabase
    .from('players')
    .insert(curatedPlayers);

  if (error) {
    console.error('Error inserting players:', error);
  } else {
    console.log(`\n🎉 Successfully seeded ${curatedPlayers.length} NFL players!`);
    console.log('\nBreakdown:');
    console.log(`  - Quarterbacks: ${curatedPlayers.filter(p => p.position === 'QB').length}`);
    console.log(`  - Running Backs: ${curatedPlayers.filter(p => p.position === 'RB').length}`);
    console.log(`  - Wide Receivers: ${curatedPlayers.filter(p => p.position === 'WR').length}`);
    console.log(`  - Defensive Players: ${curatedPlayers.filter(p => ['LB', 'DE', 'DT', 'CB', 'S'].includes(p.position)).length}`);
    console.log(`  - With photos: ${curatedPlayers.filter(p => p.photo_url).length}`);
    console.log(`  - Active players: ${curatedPlayers.filter(p => p.is_active).length}`);
  }
}

seedPlayers().catch(console.error);